### ISSUE TITLE
`SDL_SetWindowAspectRatio` sends window flying off-screen to the right.

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#11688]
Tested (on Windows) with an aspect ratio of 1.0f, when resizing the window's height to minimum, the window's x position keeps incrementing until the window is off screen.

**Comment by slouken** [comment]
Can you retest with the latest code? I'm not seeing that issue here, and I fixed a rounding issue with fixed aspect ratios.

**Comment by AntTheAlchemist** [comment]
Still happening with the latest code. Windows 10.  
```
#include <SDL3/SDL.h>
#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL_main.h>

static SDL_Window* win;

SDL_AppResult SDL_AppInit(void**, int, char**) {
	if (!SDL_Init(SDL_INIT_VIDEO))
		return SDL_APP_FAILURE;
	if (!(win = SDL_CreateWindow(nullptr, 500, 500, SDL_WINDOW_RESIZABLE)))
		return SDL_APP_FAILURE;
	SDL_SetWindowAspectRatio(win, 1.0f, 1.0f);
	return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppIterate(void*) {
	SDL_Delay(1);
	return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppEvent(void*, SDL_Event* event) {
	switch (event->type) {
	case SDL_EVENT_QUIT:
		return SDL_APP_SUCCESS;
	}
	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void*, SDL_AppResult result) {
	if (result == SDL_APP_FAILURE)
		SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Error", SDL_GetError(), nullptr);
}
```

**Comment by slime73** [comment]
What's your monitor setup? Do you have any which have a non-100% display scale? The window spontaneously changing while something else happens just reminds me of older issues like that which were DPI-related.

**Comment by AntTheAlchemist** [comment]
@slime73 I thought the same. My scale is set to 125%, but it still happens at 100%.

**Comment by AntTheAlchemist** [comment]
Project's DPI Awareness doesn't seem to make a difference either.

**Comment by AntTheAlchemist** [comment]
Increasing the width of the window to force the height to be higher than the screen causes the window to fly up and off screen.

**Comment by Kontrabant** [comment]
I can't seem to replicate this on Win 10 or 11 either. Would you be able to capture a video and event log?

**Comment by AntTheAlchemist** [comment]
Not able to capture a video. I only have xbox game bar, which records the app, not the screen, so it doesn't show the behaviour of the window while it's being resized. 

Are you using the code I posted above to repro?

**Comment by Kontrabant** [comment]
I tried both your repro code and testsprite --resizable --aspect 1.0.

With both test cases, vertically shrinking the window to the minimum doesn't move it, and resizing it so that the title bar is offscreen just causes the window to be pushed downward, so the title bar is back within desktop bounds.

**Comment by AntTheAlchemist** [comment]
https://github.com/user-attachments/assets/e6a8e066-72fd-4d8f-af83-e94853b41556

**Comment by slouken** [comment]
Fixed, thanks!
