### ISSUE TITLE
SDL_TriggerBreakpoint undefined on Linux ARM64 with gcc 9.4

### ISSUE THREAD

**Issue by Lgt2x** [libsdl-org/SDL#12443]
Hello,

I'm having trouble getting `SDL_Assert` to compile on ARM64. My build environment is Ubuntu 20.04, running gcc 9.4 targeting aarch64 using cross-compilation. I'm building SDL 3.2.4 through the VCPKG port via CMake.

The error is the following (see also the [github action build log](https://github.com/DescentDevelopers/Descent3/actions/runs/13617201265/job/38061802545?pr=675#step:15:257)):
```
‘SDL_TriggerBreakpoint’ was not declared in this scope; did you mean ‘SDL_AssertBreakpoint’?
```

`SDL_Assert` ultimately expands to `SDL_TriggerBreakpoint`, which is not defined in this case (default case in [SDL_Assert.h:160](https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_assert.h#L160))

Why do we reach this default case?
- GCC 9.4 does not define `__builtin_debugtrap` or `__builtin_trap` yet
- The next conditional directives for Linux only work for x86 and riscV
- The next ones are about Apple and Windows ARM64
- `HAVE_SIGNAL_H` is not defined

This last one is especially suspicious to me; the main SDL3 CMakeLists defines `HAVE_SIGACTION` if the `signal.h` header is found, but not `HAVE_SIGNAL_H`:

```
check_symbol_exists(sigaction "signal.h" HAVE_SIGACTION)
```

I see 2 possible mitigations here: either define the default aarch64 breakpoint the same way the [debugbreak project does](https://github.com/scottt/debugbreak/blob/master/debugbreak.h#L102), or define `HAVE_SIGNAL_H` on Linux when the `signal.h` is found

What would be the better option here?

**Comment by slouken** [comment]
This is fixed in the 3.2.6 release.

**Comment by Lgt2x** [comment]
wonderful, thanks for the lightning fast answer :)

**Comment by slouken** [comment]
You're welcome! Next time, please check the latest code before reporting bugs, thanks!

**Comment by Lgt2x** [comment]
Yes that's on me, I skimmed through the 3.2.6 release notes and did not see anything related, so I assumed it was not fixed. I will be more careful next time!

**Comment by slouken** [comment]
Thanks, we don’t add notes for every commit, just the highlights.
