### ISSUE TITLE
SDL2 window sometimes fails to gain input focus on macOS at startup

### ISSUE THREAD

**Issue by ffbh123456** [libsdl-org/SDL#13920]
On macOS, an SDL2 window usually (75%+) gains input focus and receives mouse and keyboard input automatically at startup. However, occasionally it does not, and only receives events after being minimized and restored. In those cases, clicking the window cannot give it focus.

Platform: macOS[13.2], SDL2 [2.32.8]

```c++
SDL_Window* CreateWindow()
{
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
        return nullptr;
    }

    SDL_Window* window = SDL_CreateWindow(
        "MyApp",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        960, 540,
        SDL_WINDOW_VULKAN | SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI
    );

    if (!window) {
        SDL_Quit();
        return nullptr;
    }

    SDL_RaiseWindow(window);
    SDL_SetWindowInputFocus(window);

    return window;
}

```

**Comment by slouken** [comment]
Are you seeing this with SDL3 as well?

**Comment by ffbh123456** [comment]
A few months ago, I tried SDL3 (3.2.18) but couldn’t get mouse or keyboard input to work, which is why I’m using SDL2 for now. At the time, I hadn’t tried the minimize-and-restore solution, so it might have been the same issue. Will try the latest SDL3 when I have time, though it probably won’t be very soon.

**Comment by goblinhack** [comment]
same issue on mac - SDL_WINDOW_ALWAYS_ON_TOP seemed to make it happen less often - but still does. Does that help your case a bit? (SDL2)

**Comment by icculus** [comment]
(Assigning to myself, but I'm not likely to get to this for SDL2 for awhile. If someone says this is happening in SDL3 also, though, it goes to the top of the queue.)

**Comment by goblinhack** [comment]
I noticed it happens when I move the mouse whilst starting the game. Possibly iTerm2 steals the focus while the game is starting.

**Comment by icculus** [comment]
This is possibly fixed by b2c3e6fadec4be4f16febf1b5046fe0cc950addb, which should be in 2.32.10. If anyone can upgrade and verify, I'd appreciate it.

**Comment by goblinhack** [comment]
Alas, for me I'm on 2.32.10 already. I have a workaround, check if SDL_GetKeyboardFocus is null and if so, restart the program :) Not a great workaround I'll admit. I tried quitting the SDL video/destroying the window, but on the mac these things don't seen to do anything w.r.t closing the window immediately. I'll try SDL3 at some point too

**Comment by ffbh123456** [comment]
I just upgraded to SDL3. I started and stopped my application about 10 times, and I didn’t encounter this issue. I’ll comment if I manage to reproduce it again.

However, I do have two other issues in SDL3.
https://github.com/libsdl-org/SDL/issues/14107
https://github.com/libsdl-org/SDL/issues/14108

**Comment by ffbh123456** [comment]
> same issue on mac - SDL_WINDOW_ALWAYS_ON_TOP seemed to make it happen less often - but still does. Does that help your case a bit? (SDL2)

After creating this issue, it occurs very rarely (less than 5%) in SDL2. I can’t remember whether it was caused by my code changes or by upgrading to the newest SDL2. Also, I did not use SDL_WINDOW_ALWAYS_ON_TOP.

**Comment by ffbh123456** [comment]
@icculus 
This issue still exists in the latest SDL3. Although it doesn’t occur very often, it works correctly most of the time (over 95%).

**Comment by kevinw** [comment]
Also seeing this issue in latest SDL3.

**Comment by icculus** [comment]
Just checking: if you move the mouse while launching the app, does it reproduce 100% of the time?

**Comment by goblinhack** [comment]
yes!

I have my game restart in a loop if it detects the lack of focus. I noticed
if I keep moving the mouse during restart, then the issue happens over and
over.

If I stop moving the mouse during startup, the issue is gone

So 100% related to mouse movement

thanks

**Comment by icculus** [comment]
Okay, we have something to go on here, then. Let me dig in a little deeper over here, and I'll report back.

**Comment by icculus** [comment]
> Possibly iTerm2 steals the focus while the game is starting.

iTerm2 updated when I booted the Mac today (but this update might have been many days old, this isn't my primary development system).

Today I'm noticing that I'm _always_ failing to bring the app to the foreground now with the latest SDL3. I'm also using iTerm2. Running examples/render-clear from iTerm2 never brings it to the foreground until I seek it out on the Dock. I double-clicked the examples/render-clear.app from the Finder, it doesn't have this problem. Launched the non-app-bundled examples/renderer-clear binary from the standard Terminal app...and it works correctly.

Are we _all_ using iTerm2? Could this be the culprit?

**Comment by icculus** [comment]
(Restarting iTerm2 fixed this specific problem, fwiw.)

**Comment by slouken** [comment]
> This issue started to happen from [SDL 3.2.18](https://github.com/libsdl-org/SDL/releases/tag/release-3.2.18), as older versions like 3.2.16 works fine for me.

Can you use `git bisect` to identify where it broke for you?

**Comment by icculus** [comment]
Guessing it's going to be https://github.com/libsdl-org/SDL/commit/b2c3e6fadec4be4f16febf1b5046fe0cc950addb

**Comment by icculus** [comment]
Do we have a contact at Apple still, @slouken? It would be useful if someone could tell us why this Dock trick was necessary and why nothing else needs this.

Like, what are we doing that we don't get focused on launch by default?

**Comment by icculus** [comment]
Like, is this more "oh, you didn't use a .nib file?!" fallout...?

**Comment by slouken** [comment]
> Like, is this more "oh, you didn't use a .nib file?!" fallout...?

Yeah, I think so. Launching from terminal has different finder behavior than launching from an app bundle.

**Comment by kevinw** [comment]
I found a workaround for my purposes: after creating the window, I flush the event loop completely. Then I call SDL_RaiseWindow, and flush the event loop one more time. This consistently focuses the window on startup--hope that helps any fixes here!

**Comment by goblinhack** [comment]
Kevin, you mean?

  SDL_FlushEvents(SDL_FIRSTEVENT, SDL_LASTEVENT);
  SDL_RaiseWindow(sdl.window);
  SDL_FlushEvents(SDL_FIRSTEVENT, SDL_LASTEVENT);

didn't work for me (SDL2)

thanks

**Comment by kevinw** [comment]
@goblinhack not quite (and as I mentioned, I'm on SDL3) -- I just use `while SDL_PollEvent(&evt) {}`

**Comment by goblinhack** [comment]
That worked! (SDL2)

#if __APPLE__
  SDL_Event evt;
  //
  // Work around macos focus issue, possibly caused by iTerm
  //
  while (SDL_PollEvent(&evt)) {}
#endif

  SDL_RaiseWindow(sdl.window);

**Comment by icculus** [comment]
Okay, so it sounds to me like maybe SDL just needs to wait until a certain event comes through from Cocoa, sometime after applicationDidFinishLaunching, and then do some final efforts there. I'll see if I can isolate it.

**Comment by icculus** [comment]
I don't have it yet, but assuming this is only happening when launching from the command line, I'm bumping this to 3.6.0 for now. The PollEvents/RaiseWindow workaround will work for now (and should be harmless when we fix this).

**Comment by ffbh123456** [comment]
When the issue occurs, the debug tool also stops working. Normally we can inspect variables during debugging, but when this problem happens, the debugger blocks, doesn’t show any variable data, and the program gets stuck forever. Anyone encountered the same issue?

**Comment by squidbus** [comment]
Having the same issue with SDL3, but the workaround here doesn't seem to help. Window opens with grayed out title bar as if it's unfocused, input doesn't register, and clicking the window to focus it doesn't do anything without focusing a different window first.

**Comment by bartlomiej-dawidow** [comment]
We're seeing the same problem - while working on macOS, most of the time the app does not gain focus after launching. Or more specifically it appears to be "half-focused" where it is brought to the foreground and receives mouse input, but it does not receive keyboard input. The window title bar remains greyed out, indicating that the app is unfocused.

**Comment by icculus** [comment]
Checking once again: are people:

- running these apps from the command line (vs double clicking a icon in the Finder)
- and/or running iTerm2

?


We're still trying to figure out if these things aggravate the issue.

**Comment by squidbus** [comment]
For me I recall it was running from terminal / from IDE, I believe.

**Comment by goblinhack** [comment]
yes to both for me - command line and iTerrm

**Comment by bartlomiej-dawidow** [comment]
For me, it reproduces most of the time, but not always, when starting from JetBrains Rider or from terminal. Note that the app is not bundled into an `.app`.
