### ISSUE TITLE
WASAPI WINE static sounds

### ISSUE THREAD

**Issue by kyle-sylvestre** [libsdl-org/SDL#13965]
I get static sounds when playing audio. I'm running a windows executable through wine on macOS. The static sounds are almost entirely removed when I change the system frequency to 96,000 Hz via the "Audio MIDI Setup" app. The static sounds aren't heard at all when I use DirectSound.

Version: SDL3-preview-3.1.3-225-g92520c1d9

https://github.com/user-attachments/assets/4b981d04-bac8-4e80-a958-3a3324862542

**Comment by icculus** [comment]
The closest I can find to a Windows version of this is from a shady abandonware site: https://oldgamesdownload.com/feeding-frenzy/  ...is there a more reasonable (even if paid) download somewhere?

(I actually have the source code to this--I did the Mac version--but it feels like cheating to compile my own copy.  :)  )

**Comment by icculus** [comment]
Also: 

> SDL3-preview-3.1.3-225-g92520c1d9

If this means you're using SDL 3.1.3, _please_ upgrade and see if the bug is already fixed! A lot has happened since then!

**Comment by kyle-sylvestre** [comment]
> The closest I can find to a Windows version of this is from a shady abandonware site: https://oldgamesdownload.com/feeding-frenzy/ ...is there a more reasonable (even if paid) download somewhere?
> 
> (I actually have the source code to this--I did the Mac version--but it feels like cheating to compile my own copy. :) )

This is from a version I'm building with mingw-w64-i686, I'm attempting to remake the game from assets alone. The problem should show up when playing a long enough audio file in SDL_mixer.


> Also:
> 
> > SDL3-preview-3.1.3-225-g92520c1d9
> 
> If this means you're using SDL 3.1.3, _please_ upgrade and see if the bug is already fixed! A lot has happened since then!

Updated to latest and I'm still getting the static sounds.

**Comment by mrpippy** [comment]
I'm interested in finding out where this goes, it's very possible there are buffer underruns or other bugs in Wine's CoreAudio backend. And having an easy-to-run test case (especially one with source) would be great, compared to games that have to run through Steam.

**Comment by icculus** [comment]
Tossing this in the 3.4.0 milestone, but it might slip to a later one.
