### ISSUE TITLE
Duplicate JOYDEVICEs being added when hot-plugging

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#4473]
On Windows 10 with latest source build a serious issue has been added to the joystick code recently (I previously built the DLLs in February 11th and the issue isn't there).

Most of my controllers when they are plugged in are generating a duplicated joystick called "HID-compliant game controller". The only one that doesn't is a 360 controller. A new index and instance id appears, so it looks like another physical device exists. SDL_NumJoysticks() produces a number twice as long as it should be.

This doesn't happen if the controllers are already plugged in when the app starts. 1 DEVICEADDED event for each controller/joystick appears as usual and they are only listed once with SDL_NumJoysticks(). 

Quite a serious game-breaking bug - (I miss being able to mark how serious a bug is, etc...)

SDL_HINT_JOYSTICK_HIDAPI seems to make no difference at all.

**Comment by slouken** [comment]
What controllers are you seeing this with?

**Comment by slouken** [comment]
I'm not seeing this here with a wired Xbox One controller. Also, what version of Visual Studio are you running, have you retargeted the projects for that toolchain, and what joystick support is enabled in your SDL config.h?

**Comment by slouken** [comment]
I also am not seeing the issue when I connect the controller over Bluetooth. I'm using Visual Studio 2019 with the solution retargeted for the latest toolchain, and I have the default joystick support enabled.

**Comment by AntTheAlchemist** [comment]
![log1](https://user-images.githubusercontent.com/17271828/123476382-8977d300-d5f4-11eb-9dea-8e6e10dd260e.png)
This is the event log I'm getting (interpreted & rendered in my app - top events are newest).  A load of axis events are also spat out as a controller is removed.  This is me removing the G-Shark which is Instance IDs 6&7.  Then plugging in a different joystick, which comes up as two physical joysticks. These are both wired. The first one is mapped as a controller.

If I try with an older SDL2.dll it doesn't happen. 

I'll now try with bluetooth controllers...

**Comment by AntTheAlchemist** [comment]
![log2](https://user-images.githubusercontent.com/17271828/123477604-3141d080-d5f6-11eb-88a7-db9273d5b7d6.png)
Happens with a bluetooth controller I have as well. This controller used to open as a controller with mapping, but with the latest DLL build it's lost mapping as well

**Comment by AntTheAlchemist** [comment]
![log3](https://user-images.githubusercontent.com/17271828/123477764-6a7a4080-d5f6-11eb-9b00-cca0b77fa5ec.png)
This is the same bluetooth controller running with the old DLL before the bug was introduced. This works as expected.

**Comment by AntTheAlchemist** [comment]
Keep an eye on the time stamps, you can see events come through at the same time roughly as I hot-plug

**Comment by AntTheAlchemist** [comment]
I've built both DLLs with the same process / settings. Visual Studio 2019. I don't change anything apart from the retargeting popup. I don't know about the sdl config.h - never seen it.

The only controller that doesn't do this is the Xbox controller.

**Comment by slouken** [comment]
Okay, I'm able to reproduce this with the Amazon Luna Controller. I'll take a look, thanks!

**Comment by slouken** [comment]
This is fixed by https://github.com/libsdl-org/SDL/commit/205b951b46b16ce08221c9ed17e7c518d83da4ea

Thanks!

**Comment by AntTheAlchemist** [comment]
Thanks Sam, seems better now.

Except I have a tiny Bluetooth VR controller called a Mocute-032 which opens as a mapped controller in 2.0.14 and has the name "GameStop Gamepad", but the latest source only sees it as a vanilla Joystick. Not all controllers are affected though; I'm still getting my Xbox 360 and G-Shock controllers coming up as mapped controllers.

Just wondering why mapping would disappear for this controller and if it's another issue somewhere?

**Comment by slouken** [comment]
There might be another issue. Can you open another bug and dig in to see what's happening? I don't have that device here and haven't seen any similar issue.
