### ISSUE TITLE
Windows vs SDL_WINDOW_FULLSCREEN_DESKTOP

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#4869]
Also experiencing something similar on windows, with 2.0.16.
if I run SDL_SetWindowFullscreen( window, SDL_WINDOW_FULLSCREEN_DESKTOP ); before the program starts rendering to the screen, it works fine. But when I try to switch to or from fullscreen during execution the contents of the program disappear, window is suddenly empty. I've also had it one time where only some elements disappeared, others remained.
I'm compiling with MinGW on the command line.. Don't know what more information I could supply that would be useful

__Originally posted by @Introscopia in https://github.com/libsdl-org/SDL/issues/4136#issuecomment-949272055__

**Comment by slouken** [comment]
Possibly a duplicate of https://github.com/libsdl-org/SDL/issues/4933?

**Comment by slouken** [comment]
@Introscopia I think this may have been fixed today, can you try with the latest snapshot?
http://www.libsdl.org/tmp/SDL-2.0.zip

**Comment by Introscopia** [comment]
hey! sorry, I'm a bit of a noob at compiling, couldn't figure out how to install the snapshot..

tried following the instructions:
```
C:\SDL\SDL-2.0.17-1c78b08>./configure
'.' is not recognized as an internal or external command, operable program or batch file.

C:\SDL\SDL-2.0.17-1c78b08>configure
'configure' is not recognized as an internal or external command, operable program or batch file.

C:\SDL\SDL-2.0.17-1c78b08>./configure; make; make install
'.' is not recognized as an internal or external command, operable program or batch file.

C:\SDL\SDL-2.0.17-1c78b08>make
'make' is not recognized as an internal or external command, operable program or batch file.

C:\SDL\SDL-2.0.17-1c78b08>mingw32-make
mingw32-make: *** No targets specified and no makefile found.  Stop.

C:\SDL\SDL-2.0.17-1c78b08>mingw32-make install
mingw32-make: *** No rule to make target 'install'.  Stop.
```

**Comment by slouken** [comment]
@Introscopia, you can grab the prerelease build and test with that:
https://www.libsdl.org/tmp/download-2.0.php

**Comment by Introscopia** [comment]
hey, just updated to 2.0.18, the problem persists. It seems that everything I was putting on screen with RenderCopy vanishes the moment I toggle fullscreen, FillRect and things like that still work.

**Comment by slouken** [comment]
Can you share your project so we can reproduce it here?

**Comment by Introscopia** [comment]
sent you an email!

**Comment by slouken** [comment]
This isn't actually a bug. If you use the default D3D9 renderer then you need to handle the SDL_RENDER_TARGETS_RESET event by re-creating all of your textures.

If you want to avoid that, you can use the OpenGL or D3D11 renderers, by setting one of these hints before your SDL_CreateWindowAndRenderer() call:
```c
SDL_SetHint( SDL_HINT_RENDER_DRIVER, "opengl" );
```
```c
SDL_SetHint( SDL_HINT_RENDER_DRIVER, "direct3d11" );
```

**Comment by Introscopia** [comment]
oh wow! Ok, thank you!
