### ISSUE TITLE
windowsgaminginput.c: -Wincompatible-function-pointer-types warnings

### ISSUE THREAD

**Issue by sezero** [libsdl-org/SDL#4998]
We have been having the following warning from MSVC for a long time
(see CI build logs):
```
src\joystick\windows\SDL_windows_gaming_input.c(404,1): warning C4028: formal parameter 3 different from declaration
src\joystick\windows\SDL_windows_gaming_input.c(414,1): warning C4028: formal parameter 3 different from declaration
```

And recently with clang-cl support, the following (see recent CI logs):
(messages hand-edited for better clarity):
```
src\joystick\windows\SDL_windows_gaming_input.c(408,5): warning : incompatible function pointer types initializing
 'HRESULT (*)(__FIEventHandler_1_Windows__CGaming__CInput__CRawGameController *, IInspectable *, __x_ABI_CWindows_CGaming_CInput_CIRawGameController **) __attribute__((stdcall))'
with an expression of type
 'HRESULT    (__FIEventHandler_1_Windows__CGaming__CInput__CRawGameController *, IInspectable *, __x_ABI_CWindows_CGaming_CInput_CIRawGameController * ) __attribute__((stdcall))'
 [-Wincompatible-function-pointer-types]

src\joystick\windows\SDL_windows_gaming_input.c(418,5): warning : incompatible function pointer types initializing
 'HRESULT (*)(__FIEventHandler_1_Windows__CGaming__CInput__CRawGameController *, IInspectable *, __x_ABI_CWindows_CGaming_CInput_CIRawGameController **) __attribute__((stdcall))'
with an expression of type
 'HRESULT    (__FIEventHandler_1_Windows__CGaming__CInput__CRawGameController *, IInspectable *, __x_ABI_CWindows_CGaming_CInput_CIRawGameController * ) __attribute__((stdcall))'
  [-Wincompatible-function-pointer-types]
```

This somehow _looks_ like a result from https://github.com/libsdl-org/SDL/issues/3863 patch, i.e. https://github.com/libsdl-org/SDL/commit/502cfe314aceb88e0ea00cf35a5d6f4222a3d134:
@JoelLinn, @slouken: have a look.

**Comment by slouken** [comment]
This is a bug in the SDK we're using for the CI, fixed in newer Microsoft SDK versions. Fixing this with a cast will introduce the warning for newer SDKs, so I've left it as-is.

**Comment by slouken** [comment]
Maybe we should disable the warning around those lines?

**Comment by sezero** [comment]
> This is a bug in the SDK we're using for the CI, fixed in newer Microsoft SDK versions. Fixing this with a cast will introduce the warning for newer SDKs, so I've left it as-is.

The CI logs say building with `Visual Studio 16 2019` `(MSVC 19.29.30137.0)`,
but no SDK information (if it's there, I couldn't see.)

> Maybe we should disable the warning around those lines?

IMO, we should not.

**Comment by sezero** [comment]
For what it's worth, I just built using VS2017 15.9.41 against Windows SDK 10.0.17763.0, and I get the warning.  Which SDK version is the issue supposed to be fixed?

**Comment by AntTheAlchemist** [comment]
I'm using VS2019 with Windows 10 SDK 10.0.18362.0 (the latest) and still get this warning. Is it maybe fixed for the Windows 11 SDK? I experimented to see if I could use 11SDK on Win10, and it won't let me target it.

**Comment by cgutman** [comment]
c2904c8 introduces warnings with the fixed 10.0.22000 SDK. I think we should back out that change.

**Comment by slouken** [comment]
Okay, I'll fix it for 2.0.20.

**Comment by slouken** [comment]
Actually, never mind, I'll fix it now.
