### ISSUE TITLE
Mouse button up event does not arrive when focus is lost

### ISSUE THREAD

**Issue by felkue** [libsdl-org/SDL#5301]
Reproduce the bug this way:
- Press left mouse button on an SDL window (turn mouse capturing on) and drag mouse outside the window.
- While still holding the left mouse button, press Win + Tab and select a different window using the keyboard (arrow buttons and Enter).
- Release the left mouse button.
- When we move the mouse over the SDL window again, the left mouse button seems to be still pressed (SDL_GetMouseState returns SDL_BUTTON_LMASK).
- Win + Tab and select the SDL window again (now window becomes highlighted) -> delayed mouse button up event arrives.

**Comment by sezero** [comment]
@slouken: The patch causes unwanted side effects in windowed mode:

E.g. with quakespasm in windowed mode, moving the mouse quickly while
pressing the mouse button makes the pointer go out of game window into
terminal, and with continued mouse button press makes it change the
focus to terminal. Setting the env var SDL_MOUSE_AUTO_CAPTURE=0 does
bring back old behavior, but the new behavior is ultra-confusing.

**Comment by sezero** [comment]
> @slouken: The patch causes unwanted side effects in windowed mode:
> 
> E.g. with quakespasm in windowed mode, moving the mouse quickly while pressing the mouse button makes the pointer go out of game window into terminal, and with continued mouse button press makes it change the focus to terminal. Setting the env var SDL_MOUSE_AUTO_CAPTURE=0 does bring back old behavior, but the new behavior is ultra-confusing.
> 
> EDIT: This is with Linux + X11, btw.

It also affects SDL-1.2 games running under sdl12-compat, naturally.

Reopening so this doesn't get lost before 2.0.22

**Comment by sezero** [comment]
@slouken, @icculus: Would it be OK to change the hint's default to disabled at least?
```diff
diff --git a/include/SDL_hints.h b/include/SDL_hints.h
index b61eb32..9ef7d2f 100644
--- a/include/SDL_hints.h
+++ b/include/SDL_hints.h
@@ -989,10 +989,10 @@ extern "C" {
  *  \brief  A variable controlling whether the mouse is captured while mouse buttons are pressed
  *
  *  This variable can be set to the following values:
- *    "0"       - The mouse is not captured while mouse buttons are pressed
+ *    "0"       - The mouse is not captured while mouse buttons are pressed (default)
  *    "1"       - The mouse is captured while mouse buttons are pressed
  *
- *  By default the mouse is captured while mouse buttons are pressed so if the mouse is dragged
+ *  If enabled, the mouse is captured while mouse buttons are pressed so if the mouse is dragged
  *  outside the window, the application continues to receive mouse events until the button is
  *  released.
  */
diff --git a/src/events/SDL_mouse.c b/src/events/SDL_mouse.c
index 092c95f..ad6a4af 100644
--- a/src/events/SDL_mouse.c
+++ b/src/events/SDL_mouse.c
@@ -153,7 +153,7 @@ static void SDLCALL
 SDL_MouseAutoCaptureChanged(void *userdata, const char *name, const char *oldValue, const char *hint)
 {
     SDL_Mouse *mouse = (SDL_Mouse *)userdata;
-    SDL_bool auto_capture = SDL_GetStringBoolean(hint, SDL_TRUE);
+    SDL_bool auto_capture = SDL_GetStringBoolean(hint, SDL_FALSE);
 
     if (auto_capture != mouse->auto_capture) {
         /* Turn off mouse capture if it's currently active because of button presses */
```

**Comment by slouken** [comment]
No. I'll try to spend some time this weekend thinking this through. It may be that capturing the mouse isn't working the way we expect on X11.

**Comment by sezero** [comment]
Well, something needs to be done - games I try are unplayable with this.

**Comment by sezero** [comment]
Possibly related: https://github.com/libsdl-org/SDL/issues/5457

**Comment by slouken** [comment]
@sezero, I just tried with Ubuntu 22.04 using the current SDL and the quakespasm package, and wasn't able to reproduce the issue. The mouse remained captured and didn't leave the window. It looks like it's using Xwayland, maybe that matters? Can you provide more information about your environment?

**Comment by slouken** [comment]
FWIW, I also got the mouse up event in testsprite2, when clicking in the window and dragging out, with the current code.

**Comment by sezero** [comment]
> @sezero, I just tried with Ubuntu 22.04 using the current SDL and the quakespasm package, and wasn't able to reproduce the issue. The mouse remained captured and didn't leave the window. It looks like it's using Xwayland, maybe that matters? Can you provide more information about your environment?

This is CentOS 6.10, i686, X-only, gnome2. Possibly related X rpms:
xorg-x11-server-Xorg-1.17.4-18.el6.centos.i686
xorg-x11-server-common-1.17.4-18.el6.centos.i686
libXext-1.3.3-1.el6.i686
libXfixes-5.0.3-1.el6.i686
libXxf86vm-1.1.3-2.1.el6.i686
libXxf86misc-1.0.3-4.el6.i686
libXxf86dga-1.1.4-2.1.el6.i686
libxcb-1.12-4.el6.i686
libxkbfile-1.0.6-1.1.el6.i686
xcb-util-keysyms-0.4.0-1.el6.i686
xorg-x11-xkb-utils-7.7-12.el6.i686
xorg-x11-server-utils-7.7-14.el6.i686
xorg-x11-utils-7.5-14.el6.i686
xorg-x11-drivers-7.3-13.4.el6.i686

Do you need anything else?

**Comment by sezero** [comment]
> > @sezero, I just tried with Ubuntu 22.04 using the current SDL and the quakespasm package, and wasn't able to reproduce the issue. The mouse remained captured and didn't leave the window. It looks like it's using Xwayland, maybe that matters? Can you provide more information about your environment?
> 
> This is CentOS 6.10, i686, X-only, gnome2. Possibly related X rpms: xorg-x11-server-Xorg-1.17.4-18.el6.centos.i686 xorg-x11-server-common-1.17.4-18.el6.centos.i686 libXext-1.3.3-1.el6.i686 libXfixes-5.0.3-1.el6.i686 libXxf86vm-1.1.3-2.1.el6.i686 libXxf86misc-1.0.3-4.el6.i686 libXxf86dga-1.1.4-2.1.el6.i686 libxcb-1.12-4.el6.i686 libxkbfile-1.0.6-1.1.el6.i686 xcb-util-keysyms-0.4.0-1.el6.i686 xorg-x11-xkb-utils-7.7-12.el6.i686 xorg-x11-server-utils-7.7-14.el6.i686 xorg-x11-utils-7.5-14.el6.i686 xorg-x11-drivers-7.3-13.4.el6.i686
> 
> Do you need anything else?

FWIW, just reproduced on fedora-27 / x86_64 with Xwayland: xserver 1.19.6.

**Comment by slouken** [comment]
@icculus, I can't reproduce this, can you take a look?

**Comment by icculus** [comment]
Tried this with the Ubuntu quakespasm package, Ubuntu 21.10, using real x.org, no Wayland. Verified it's using the latest git version of SDL2.

The game works, but I can see the mouse cursor leave the window. Easiest reproduction case here:

- Launch the game
- Choose "single player"
- When you start, just fire the shotgun with the left mouse button and move the mouse up until it leaves the window. You can see the system cursor leave the top of the window. It's not a timing thing, you can click the mouse and then take your time rolling out of the window.

Seems to be associated with mouse clicks; it won't leave unless you press the mouse button. If you bring the cursor back into the window the cursor will hide/grab again and everything will work as expected.

When the mouse leaves the window, it looks like relative mouse mode still works (even when the cursor hits the edge of the desktop, you can still keep spinning the player infinitely in that direction).

**Comment by slouken** [comment]
@sezero, your issue should be fixed in https://github.com/libsdl-org/SDL/commit/86acb1a347fb232f0211864fe00af2d7590a3717

**Comment by sezero** [comment]
It is, yes. Thank you.

**Comment by sezero** [comment]
@slouken: A regression was reported at https://discourse.libsdl.org/t/sdl-2-0-22-prerelease/35306/21 after this.

**Comment by dos1** [comment]
https://github.com/libsdl-org/SDL/issues/5924 is also a regression caused by this (and despite of its title, it affects all X11 desktops, not just Phosh or XWayland).

**Comment by misl6** [comment]
Hi!

We are encountering the same exact original issue, but on Windows 11 (See: https://github.com/kivy/kivy/issues/8238).
I've tried to set `SDL_MOUSE_AUTO_CAPTURE` to `0`, but unfortunately the issue persists.

The bug seems to be present on the following versions:
- SDL version: `2.26.4` ( via https://pypi.org/project/kivy-deps.sdl2/0.6.0/)
- SDL version: `2.24.1` ( via https://pypi.org/project/kivy-deps.sdl2/0.5.1/)
- SDL version `2.24.0` (via https://pypi.org/project/kivy-deps.sdl2/0.5.0/)

Instead, SDL version `2.0.20` (via https://pypi.org/project/kivy-deps.sdl2/0.4.5/) does not seem be affected.

Feel free to ping me if you need any additional info or help to test changes.

**Comment by slouken** [comment]
Please report this as a new issue, as this one is already closed and specific to X11.

Thanks!
