### ISSUE TITLE
Blank screen on older Android devices since 5858c7dfce80b0854b04475dde97996692ce9200 (Actually, OpenGLES2 is broken on Windows as well)

### ISSUE THREAD

**Issue by AntTheAlchemist** [libsdl-org/SDL#6166]
Used to work before this commit. Example of older Android versions are 5.1.1 Nexus Tablet and 4.2.2 Chinese TV Stick.

Just now tested on Windows and when I use the OpenGLES2 renderer it doesn't draw anything on that platform either.

**Comment by slime73** [comment]
(Here's a link to the commit so it's easier to see: https://github.com/libsdl-org/SDL/commit/5858c7dfce80b0854b04475dde97996692ce9200)

I'm a little confused by the change - which systems that run OpenGL ES 2 shaders don't support precision keywords? Those keywords are a mandatory part of the OpenGL ES 2 shading language specification https://registry.khronos.org/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf

The only one that isn't guaranteed full support on all systems is `highp` in fragment shaders, which the `GL_FRAGMENT_PRECISION_HIGH` define can detect support for (only in fragment shaders). But `precision`, `mediump`, etc all should work in all situations.

**Comment by eloj** [comment]
I think I experienced this on desktop Linux Mint 21.0/X11 recently when, for whatever reason that is not imporant, the system upgrade to Mint 21 decided to uninstall `libgl-dev`. This caused SDL not render anything but otherwise function as expected. The only 'rendering' that still worked was `SDL_RenderClear`.

I didn't report it because initially I wasn't sure if the GLES2 path was _supposed to work on desktop_ and after some digging I realized what had happened with my system setup and corrected it.

**Comment by 1bsyl** [comment]
@slime73 
not sure, but sometimes there is
#if GL_FRAGMENT_PRECISION_HIGH

and sometimes
#ifdef GL_FRAGMENT_PRECISION_HIGH


@eloj 
can you log the error of SDL_GetError() ?

**Comment by eloj** [comment]
@1bsyl:
>  can you log the error of SDL_GetError() ?

Yes. There's an error in the shader code somewhere. If I put a check in my main render loop and launch with `SDL_RENDER_DRIVER=opengles2 ./program`

```
SDL error: 'Failed to load the shader: 0(2) : error C0105: Syntax error in #if
0(2) : error C0105: Syntax error in #if
'
```

**Comment by slime73** [comment]
> Checking for `GL_FRAGMENT_PRECISION_HIGH` makes sense, but surely only to redefine highp to mediump?

Even this shouldn't be necessary: the commit prior to 5858c7d was the one which added uses of `highp`, and it already covered them with `#ifdef GL_FRAGMENT_PRECISION_HIGH`: https://github.com/libsdl-org/SDL/commit/65647b341777e469efc9a3e05755eb89daed4ecc 

We also don't want to use `highp` in places where it wouldn't make a visible improvement to output, since it is slower than `mediump` on various phones.

**Comment by eloj** [comment]
For the immediate problem, it seem to me it comes down to either change the `SHADER_PRELOGUE`\[sic\] to unconditionally set the default precision to `mediump`, or fix all the places where it's missing. OpenGLES2 is broken everywhere now.

Then always rely on "at time and place" checks for `GL_FRAGMENT_PRECISION_HIGH` for specific use of `highp`.

Bonus task: Compile shaders up-front and propagate error back through `SDL_CreateRenderer()`.

**Comment by AntTheAlchemist** [comment]
Just tested the latest source and OpenGLES isn't working on any platform now. On my Nokia 8 I'm getting a blank screen and this error in Logcat: "I/AdrenoGLES-0: ERROR: Invalid #version". I'm still getting a blank screen on Windows 10, Nexus 7, and Rockchip Chinese TV stick . I had no problem on these platforms before the precision fix on Aug 6.

**Comment by slime73** [comment]
@slouken I don't have a suitable setup to test the same type of situation you were running into on desktop, but I noticed the GLES2 (and GLES1) renderer backend has some code in its initialization functions to try to detect when there's not actually a GLES context active (ie when there might be a desktop GL context instead). It tries to recreate things in that case but it might not properly fail out when it's still not a GLES(2) context.

I wonder if that's the type of scenario you've been running into? In my opinion if the GLES2 render backend isn't able to run inside a GLES2 context it should error during creation. It's one avenue of investigation at the very least.

Inside a GLES(2) context, `glGetString(GL_VERSION)` will always return a string that starts with "OpenGL ES [version number here]".

**Comment by 1bsyl** [comment]
@slouken 
On linux, creating the GLES2 renderer now fails with:

```
Failed to load the shader: 0:7(40): error: No precision specified in this scope for type `vec4'
0:8(2): error: No precision specified in this scope for type `vec2'
```

it used to work before

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/bc57d3e35ce0067a1098ef72857351fcf93469b3, thanks!

**Comment by 1bsyl** [comment]
Thanks, it works!

**Comment by AntTheAlchemist** [comment]
Looks good from here, thanks. 

I pulled out my old Asus Win10 tablet to test it on, because SDL's OpenGLES2 driver was always a bit glitchy on it. I get this error: "Failed to load the shader 6: ERROR: 0:2: '#extension': 'GL_OES_EGL_image_external' is not supported" "ERROR: 2:1: 'u_texture' : syntax error syntax error".

... which for me is OK because if SDL_CreateRenderer fails when I request the ES2 renderer, then I can just try again with index "-1". Might explain why ES2 was always a bit glitchy on this tablet in the past.

Does the above error show something else wrong? Or is it all good now?

**Comment by slouken** [comment]
Hmm, we should probably make that shader optional. Let me think about that...

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/5bc85d67880a3bc8f67a9a451eca41f99a47de92, thanks!

**Comment by AntTheAlchemist** [comment]
> Fixed in [5bc85d6](https://github.com/libsdl-org/SDL/commit/5bc85d67880a3bc8f67a9a451eca41f99a47de92), thanks!

@slouken Thanks. Now GLES2 is going through ok, I notice this renderer is still glitchy on this tablet. Everything is white-wished, like the brightness is up really high - it's been this way for years, not an issue because this tablet works in Dx3D & OpenGL. And the openGL error still gets set even though the renderer returns ok. Not sure if these are issues.
