### ISSUE TITLE
[Critical]SDL3 would crash when resizing the window!

### ISSUE THREAD

**Issue by huangjinshe** [libsdl-org/SDL#8528]
After we created a window, started to play video, updated texture from frames, if we **resizing the window size slowly**, **the SDL will crash**.

The SDL2 will not crash. all normal.  SDL2 will also automatically fix the render area in the window,  but SDL3 render are not update after resize.

![sdl3](https://github.com/libsdl-org/SDL/assets/3822799/2b8016f0-c69c-42bd-af5f-b3425cfa141e)

SDL2 version: (2.28.3) 
The SDL3 download from [here](https://github.com/libsdl-org/SDL/actions/runs/6727292562).  (build on 2023.11.12)

For you guys replicate the problem easily,  I made some sample projects. you could directly run it and test.(All code are same, only `SDL2.dll` and `SDL3.dll` different in it)

SDL3 crash:
[WindowsProject_SDL_Crash(SDL3).zip](https://github.com/libsdl-org/SDL/files/13321425/WindowsProject_SDL_Crash.SDL3.zip)

SDL2 normal:
[WindowsProject_SDL_Crash(SDL2).zip](https://github.com/libsdl-org/SDL/files/13321437/WindowsProject_SDL_Crash.SDL2.zip)

**Comment by slouken** [comment]
If you look, you've got resize handling on the main thread:
```
DDITraits<1,2>::GetpfnExecuteCommandLists(unsigned __int64)
TableFunctionTraits<2>::Detail::InvokerImpl<struct TableFunctionTraitsImpl<2>::FunctionTraits<52,2,void>,void,void,struct D3D12DDI_HCOMMANDQUEUE,unsigned int,struct D3D12DDI_HCOMMANDLIST const *>::Call<class CCommandQueue<0> >(class CCommandQueue<0> *,struct D3D12DDI_HCOMMANDQUEUE,unsigned int,struct D3D12DDI_HCOMMANDLIST const *)
CCommandQueue<0>::ExecuteCommandListsImpl(unsigned int,struct ID3D12CommandList * const *)
CCommandQueue<0>::ExecuteCommandLists(unsigned int,struct ID3D12CommandList * const *)
D3D12_IssueBatch(D3D12_RenderData *)
D3D12_CreateWindowSizeDependentResources(SDL_Renderer *)
D3D12_UpdateForWindowSizeChange(SDL_Renderer *)
D3D12_WindowEvent(SDL_Renderer *, const SDL_WindowEvent *)
SDL_RendererEventWatch(void *, SDL_Event *)
SDL_PushEvent_REAL(SDL_Event *)
SDL_SendWindowEvent(SDL_Window *, SDL_EventType, int, int)
SDL_CheckWindowPixelSizeChanged(SDL_Window *)
SDL_OnWindowResized(SDL_Window *)
SDL_SendWindowEvent(SDL_Window *, SDL_EventType, int, int)
WIN_WindowProc(HWND__ *, unsigned int, unsigned __int64, __int64)
UserCallWinProcCheckWow()
DispatchClientMessage()
__fnINLPWINDOWPOS()
KiUserCallbackDispatcherContinue()
NtUserMessageCall()
RealDefWindowProcWorker()
RealDefWindowProcW()
DoMsgDefault(struct _THEME_MSG const *)
OnDwpSysCommand()
_ThemeDefWindowProc(struct HWND__ *,unsigned int,unsigned __int64,__int64,int)
ThemeDefWindowProcW()
DefWindowProcW()
WndProc(HWND__ *, unsigned int, unsigned __int64, __int64)
```
at the same time as rendering on the render thread:
```
CGraphicsCommandList::DrawInstanced_VariadicHelper<void ,0,1,0,0>::Variadic_Thk(struct ID3D12GraphicsCommandListNext *,unsigned int,unsigned int,unsigned int,unsigned int)
D3D12_DrawPrimitives(SDL_Renderer *, D3D_PRIMITIVE_TOPOLOGY, const unsigned __int64, const unsigned __int64)
D3D12_RunCommandQueue(SDL_Renderer *, SDL_RenderCommand *, void *, unsigned __int64)
FlushRenderCommands(SDL_Renderer *)
SDL_RenderPresent_REAL(SDL_Renderer *)
SDL_RenderPresent(SDL_Renderer *)
wWinMain::__l2::<lambda_1>::operator()()
```
You're basically guaranteed to crash with this setup.

If you need to structure your application this way, you can try using D3D11, which has a strong thread-safety model:
```c
    SDL_SetHint( SDL_HINT_RENDER_DIRECT3D_THREADSAFE, "1" );
    
    renderer = SDL_CreateRenderer(Window, "direct3d11", SDL_RENDERER_ACCELERATED);
```

**Comment by huangjinshe** [comment]
I hope reopen this issue,  it only little better, but not fixing the issue.
1.When resizing, still can't render to full window, there are some area in the bottom always not render correctly.

![problem1](https://github.com/libsdl-org/SDL/assets/3822799/d57dbdd7-c6f7-4866-aaeb-573e61d21f5c)

2.When resizing it still possible to crash. you could try more

![problem2](https://github.com/libsdl-org/SDL/assets/3822799/12c8a71c-be34-416f-b8bb-0937ba2b8c76)


3.When pausing the render and resizing, SDL3 only change the window size, but render area still same size as before,  I think the window should be change to black as like SDL2(Or render area should fill to window?  I don't knwo).
4.If we need to set rendering driver as `direct3d11`, I worry it will conflict with alpha transparency, just like the previous problem.

**Comment by slouken** [comment]
Try rendering and handling events on the same thread. Multi-threaded rendering is not supported in the existing SDL renderers.

**Comment by huangjinshe** [comment]
I removed the `SDL_SetWindowSize` with `WM_SIZE` in `WndProc`
```
// remove this logic or WM_SIZE
//SDL_SetWindowSize(Window, newWidth, newHeight);
```

As you see it's in the same thread right now.

```
std::thread thread = std::thread([&]
    {
        while (!quit)
        {
            std::unique_lock<std::mutex> lock(mtx);
            SDL_Event event;
            bool quit = false;
            while (!SDL_PollEvent(&event))
            {
                SDL_Delay(100);
                for (int i = 0; i < 400 * 400; i++)
                {
                    pixels[i] = rand();
                }
                SDL_UpdateTexture(texture, NULL, pixels, 400 * sizeof(Uint32));
                SDL_RenderClear(renderer);
                SDL_RenderTexture(renderer, texture, NULL, NULL);
                SDL_RenderPresent(renderer);
                SDL_PumpEvents();
            }

            if (event.type == SDL_EVENT_QUIT)
            {
                quit = true;
            }
            else if (event.window.type == SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED)
            {
                ReCreate();
            }
        }
    });
thread.detach();
```
There is only 1 thread call `thread` it will handle event or rendering.  It all normal in `SDL2`. only the `SDL3` crash right now.

**Comment by slouken** [comment]
If you look in the debugger, it's not in the same thread. The Windows message dispatch is happening in the main thread.

**Comment by huangjinshe** [comment]
As you see I can't put the render into the windows dispatch thread.   It might block the UI, or slow down, freeze it.  
I don't know why you guys change it like this way, SDL2 no this issue.
In our many cases, we are not able to put all in same thread.   If we're using other framework in windows like Winform,  WPF, WinUI, UWP, Xamarin we always call unmanaged code from c++,  how could we binding the UI thread with the thread which responsible to render in SDL3? That's why I made this kind of sample for you understand what we will facing in the real life.

**Comment by slouken** [comment]
I'm pretty sure you'll run into the same issue using directx12 renderer on SDL2. Can you provide an SDL2 version of this that works?

**Comment by huangjinshe** [comment]
Actually I uploaded the same sample for you with different version of SDL, you could download and try, you will find out the difference,  I mentioned earlier about resizing, pausing, render area, they still have some difference.  I hope you could quickly read the issue one more time. (no offence,  just for you more understanding clearly)

**Comment by slouken** [comment]
Thank you for clarifying, I see it now.

If you take your SDL2 example and change the renderer to D3D12, it'll crash in the same way:
```
    SDL_SetHint( SDL_HINT_RENDER_DRIVER, "direct3d12" );
    renderer = SDL_CreateRenderer(Window, -1, SDL_RENDERER_ACCELERATED);
```

If you take your SDL3 example and change the renderer to D3D9, it'll work the way you want:
```
    renderer = SDL_CreateRenderer(Window, "direct3d", SDL_RENDERER_ACCELERATED);
```

**Comment by slouken** [comment]
I think this is fixable though, let me play with it a bit.

**Comment by huangjinshe** [comment]
Wow....in that case, I think we better have a good solution for this, because use ui dispatcher thread for render is not a good solution for us.

That's a really good news that you have a plan.

**Comment by slouken** [comment]
This should be fixed in 843873626, can you try it out?

**Comment by huangjinshe** [comment]
The crash problem solved.  I download the source code open the `SDL-main\VisualC\SDL.sln` by VS2012, buld it as Win32. And replace the SDL.dll and SDL.lib in this sample project, it worked. only little problem like the render area still not complete but it will restore after we move the window. However it's not a big deal, not crash is the biggest help,  thanks.

![test2](https://github.com/libsdl-org/SDL/assets/3822799/4e4d3e7f-49f4-47cf-b5f2-aa6d396b89ec)

**Comment by slouken** [comment]
You're welcome!
