### ISSUE TITLE
Camera api returns weird surface

### ISSUE THREAD

**Issue by captain1947** [libsdl-org/SDL#9368]
`SDL_AcquireCameraFrame()` returns a strange surface. This happens even after `SDL_GetCameraPermissionState()` starts returning 1. I first spotted this while playing around with the API but the testcamera example also has the same problem. I am on windows and built the SDL3 pre-release with the msys2 ucrt64 toolchain. My camera is a built-in laptop camera.
Just to clarify I can see myself on the screen but the image/surface has a lot of artefacts and a greenish tinge.

**Comment by Green-Sky** [comment]
A picture would help with the diagnosis :)
To me this sounds like the planes are potentially swapped.

**Comment by captain1947** [comment]
Sorry, for replying late. I did some more digging and this is caused due to the issues mentioned in https://github.com/libsdl-org/SDL/issues/9504. In my case the native pixel format of the surface is SDL_PIXELFORMAT_NV12. The software and the vulkan backends work correctly because probably they support the format. The opengl and direct3d11 backend show the problem I mentioned above and the direct3d12 backend just segfaults.

**Comment by captain1947** [comment]
And this is the kind of image I get if I keep a white sheet in front of the camera.
![image](https://github.com/libsdl-org/SDL/assets/87000456/11c17aa5-503a-43a3-95c0-419300c279f7)

**Comment by slouken** [comment]
The OpenGL, D3D11 and D3D12 backends all support NV12 textures. It sounds like you have some sort of alignment issue with your image. What API function are you using to update the texture, and what are you passing for the pitch values, if any?

**Comment by captain1947** [comment]
The issue is reproducible with the testcamera example as I mentioned above. And this is what it seems to do `SDL_UpdateTexture(texture, NULL, frame_current->pixels, frame_current->pitch);` (line 245). Also, it seems to create the format with the correct format.

**Comment by slouken** [comment]
Can you attach the raw pixel data and the pitch value?

**Comment by captain1947** [comment]
Continuing from discord...
The pitch value is 1280 and here is the file  
[pixels.zip](https://github.com/libsdl-org/SDL/files/15179700/pixels.zip)
And as I noted in discord if I save the frame with IMG_SavePNG I get the correct expected image.

**Comment by Green-Sky** [comment]
You either need to convert your surface to an RGB(A) format, or use [SDL_Update**NV**Texture](https://wiki.libsdl.org/SDL3/SDL_UpdateNVTexture) instead.

**Comment by captain1947** [comment]
The converting to RGBA way works as expected. But I am more interested in the SDL_UpdateNVTexture way. The docs mention that we can use SDL_UpdateTexture as long as the pixel data is a contiguous block of NV12/21 planes in the proper order. So, ig in this case it's not contiguous.
I have no idea how to use SDL_UpdateNVTexture correctly though. Can you help me to feed it the correct arguments?

**Comment by Green-Sky** [comment]
Hm, did you lock the surface before accessing `pixels`? I also am not sure you *can* extract the planes from `SDL_Surface`.

**Comment by captain1947** [comment]
No, I followed the testcamera examples because there was no other source to learn how to use the API and the example doesn't seem to lock/unlock the texture.

**Comment by captain1947** [comment]
Hmm strangely the person who wrote the example also uses SDL_TEXTURE_STATIC flag while creating the texture, which is contradictory if I understand the flag correctly.

**Comment by Green-Sky** [comment]
Yea, I noted the STATIC usage in the original pr, but I guess I was ignored...

In most cases however the performance of using static like this is not going to be extremely bad. :)

**Comment by captain1947** [comment]
And locking/unlocking the surface doesn't help also SDL_MUSTLOCK evaluates to 0 confirming that locking is not necessary here.

**Comment by icculus** [comment]
> Hm, did you lock the surface before accessing pixels? I also am not sure you can extract the planes from SDL_Surface.

Currently SDL_Surface expects the planes to be contiguous and tightly packed, so you _can_ extract the planes from it. We have an issue open to allow a surface to have multiple planes, but nothing has come of it yet.

> Hmm strangely the person who wrote the example also uses SDL_TEXTURE_STATIC flag while creating the texture, which is contradictory if I understand the flag correctly.

That's a bug (that's probably unrelated to this one) that we haven't had time to deal with yet. Sorry about that!

**Comment by captain1947** [comment]
> Currently `SDL_Surface` expects the planes to be contiguous and tightly packed, so you can extract the planes from it. We have an issue open to allow a surface to have multiple planes, but nothing has come of it yet.  
Oh, ok. But I don't understand if it's the surface then why drawing the surface with old Surface API, software rendering, saving the surface with `IMG_SavePNG` and the Vulkan renderer don't have issue? The issue is only seen when I use functions like `SDL_UpdateTexture` or `SDL_CreateTextureFromSurface` (with a renderer other than Vulkan or software). Anyways, I hope that things will become somewhat more clear if/when Sam takes a look at the pixel dump.

> That's a bug (that's probably unrelated to this one) that we haven't had time to deal with yet. Sorry about that!
No need to be sorry lol. We greatly appreciate the effort you guys put in maintaining SDL.

**Comment by slouken** [comment]
FYI, I'm able to reproduce this here. I'm taking a look.

**Comment by slouken** [comment]
Okay, I fixed the D3D11 renderer when using NV12 textures. I didn't see an issue with OpenGL and D3D12 and testcamera worked for me with those renderers. Does it work for you, or are you just seeing this issue in your own code?

**Comment by slouken** [comment]
(also I switched testcamera to use streaming textures)

**Comment by captain1947** [comment]
> Okay, I fixed the D3D11 renderer when using NV12 textures. I didn't see an issue with OpenGL and D3D12 and testcamera worked for me with those renderers. Does it work for you, or are you just seeing this issue in your own code?

Hmm opengl seems to be working fine now, I recently pulled SDL and also updated my graphics drivers so it can be either of those (amd opengl drivers are known to have problems). The code I am testing upon is testcamera.c (I just removed the SDL_test stuff and manually created the renderer and the window because I was unsure how to modify the test stuff to change the renderer backend).
And D3D12 still crashes with `DEBUG: __FUNCTION__, D3D12_IssueBatch: Unspecified error`. I tested on all the other backends and they seem to be working fine.

**Comment by slouken** [comment]
You can pass command line parameters to testcamera, e.g. --renderer direct3d12

**Comment by captain1947** [comment]
I pulled the latest changes and the original issue seems to be fixed. Direct3d12 backend still crashes with that error but I think that is a separate issue which I will try to track down. You can close this issue if you want to. And thank you for looking into and fixing the problem.

**Comment by slouken** [comment]
You're welcome!
