### ISSUE TITLE
X11 window opens on the wrong display

### ISSUE THREAD

**Issue by slouken** [libsdl-org/SDL#9915]
@Kontrabant, it looks like your recent changes have introduced a regression in the X11 window positioning:
https://github.com/ValveSoftware/Dota-2/issues/2712

It looks like the floating window position doesn't have the correct coordinates for the requested display. You can reproduce this with: testwm --display 1

**Comment by slouken** [comment]
Actually, the testwm repro is a bug in the SDL_test library. Something else is going on with DOTA.

**Comment by Kontrabant** [comment]
Hmm, from that issue, it looks like specifying a display using the `-sdl_displayindex` parameter works correctly, so it might be something with how Steam passes the requested display to the game when using `-phased_window_create`?

**Comment by slouken** [comment]
DOTA is requesting a position of 0,0, but being placed on the second monitor. I'm not sure why this is coming up now, but I'm investigating. I'll let you know if I need help with any of the pending operation code that you added.

**Comment by slouken** [comment]
Something is happening internally to SDL:
```
INFO: SDL3CALL SDL_CreateWindowWithProperties
INFO: y: 0 (0)
INFO: x: 0 (0)
INFO: title: "Dota 2"
INFO: flags: 268435473 (10000011)
INFO: height: 2160 (870)
INFO: width: 3840 (f00)
INFO: SDL EVENT: SDL_EVENT_WINDOW_SHOWN (timestamp=278598346 windowid=3 event=SDL_EVENT_WINDOW_SHOWN data1=0 data2=0)
INFO: SDL EVENT: SDL_EVENT_WINDOW_EXPOSED (timestamp=278881375 windowid=3 event=SDL_EVENT_WINDOW_EXPOSED data1=0 data2=0)
INFO: SDL EVENT: SDL_EVENT_WINDOW_FOCUS_GAINED (timestamp=278911364 windowid=3 event=SDL_EVENT_WINDOW_FOCUS_GAINED data1=0 data2=0)
INFO: SDL EVENT: SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED (timestamp=279547046 windowid=3 event=SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED data1=3840 data2=2160)
INFO: SDL EVENT: SDL_EVENT_WINDOW_MOVED (timestamp=279558551 windowid=3 event=SDL_EVENT_WINDOW_MOVED data1=3840 data2=0)
INFO: SDL EVENT: SDL_EVENT_WINDOW_DISPLAY_CHANGED (timestamp=279563393 windowid=3 event=SDL_EVENT_WINDOW_DISPLAY_CHANGED data1=2 data2=0)
INFO: SDL EVENT: SDL_EVENT_WINDOW_TAKE_FOCUS (timestamp=289909884 windowid=3 event=SDL_EVENT_WINDOW_TAKE_FOCUS data1=0 data2=0)
INFO: SDL EVENT: SDL_EVENT_KEY_DOWN (timestamp=300197442 windowid=3 which=0 state=pressed repeat=false scancode=15 keycode=108 mod=0)
INFO: SDL EVENT: SDL_EVENT_WINDOW_TAKE_FOCUS (timestamp=323323410 windowid=3 event=SDL_EVENT_WINDOW_TAKE_FOCUS data1=0 data2=0)
INFO: SDL3CALL SDL_DestroyProperties
```

**Comment by slouken** [comment]
I can reproduce this using the same window creation options with testwm:
`./test/testwm --vulkan-window --renderer vulkan --fullscreen-desktop --noframe`

**Comment by slouken** [comment]
It also works with OpenGL:
`./test/testwm --opengl-window --renderer opengl --fullscreen-desktop --noframe`

**Comment by slouken** [comment]
Removing `--noframe` fixes it in the test case, which doesn't make any sense...

**Comment by Kontrabant** [comment]
This doesn't seem to want to reproduce on my system (Fedora 40+GNOME 46). Even with both displays set to the same resolution, the window is always placed where it should be on real X11 and XWayland.

A couple of starting points:
- Trying commenting out lines 660-665 in SDL_x11window.c. This was a workaround added to fix a fullscreen flickering issue (also for DOTA), which may not be needed anymore with commit ad813a6. Removing --noframe will bypass this, so that's why this comes to mind.
- Bisect to commit ad813a6 , as that is the only real place where any code dealing with positioning changed in recent history.

**Comment by slouken** [comment]
>     * Trying commenting out lines 660-665 in SDL_x11window.c. This was a workaround added to fix a fullscreen flickering issue (also for DOTA), which may not be needed anymore with commit [ad813a6](https://github.com/libsdl-org/SDL/commit/ad813a65e791d295351e70b2d1c36b06f3853999). Removing --noframe will bypass this, so that's why this comes to mind.

Yup, this fixes it.

**Comment by slouken** [comment]
However if I remove that, borderless windows are no longer borderless.

**Comment by slouken** [comment]
It looks like at the point we call X11_CreateWindow(), pending_flags hasn't been set up, and there's no opportunity for fullscreen_exclusive to be set, so this logic seems suspect. I think what you're trying to do is skip this for fullscreen windows, but there's currently no way to tell at this point.

**Comment by slouken** [comment]
I assume this used to work and something changed so these flags aren't set up the way you expect now?

**Comment by Kontrabant** [comment]
I think I see what is happening:

A flag is set to ignore size and position events during the initial configuration, since window managers can initially send garbage coordinates (GNOME initially creates windows _way_ out of bounds for some reason), but that flag is being overridden if the borders appear during this process, leading to the garbage coordinates being used.

I'll have a pull ready for you to try shortly.

**Comment by slouken** [comment]
BTW, if I try before commit https://github.com/libsdl-org/SDL/commit/ad813a65e791d295351e70b2d1c36b06f3853999 I still have broken behavior, but the testwm window gets continuous motion events, bouncing between monitors:
```
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 3840,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 3840,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 3840,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 3840,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 3840,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
INFO: Window 3 moved to 0,0 (display ASUS PA329CV 32")
```

**Comment by Kontrabant** [comment]
That's expected, as that was exactly the behavior that commit was intended to fix (again, due to the compositor initially sending garbage coordinates).

**Comment by slouken** [comment]
Great, I have a good repro case then. :)

If your change works, do we want to unconditionally set the window bordered state?
```diff
diff --git a/src/video/x11/SDL_x11window.c b/src/video/x11/SDL_x11window.c
index 02737c648..510faf881 100644
--- a/src/video/x11/SDL_x11window.c
+++ b/src/video/x11/SDL_x11window.c
@@ -655,14 +655,7 @@ int X11_CreateWindow(SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesI
         return SDL_SetError("Couldn't create window");
     }
 
-    /* Do not set borderless window if in desktop fullscreen, this causes
-       flickering in multi-monitor setups */
-    if (!((window->pending_flags & SDL_WINDOW_FULLSCREEN) &&
-          (window->flags & SDL_WINDOW_BORDERLESS) &&
-          !window->fullscreen_exclusive)) {
-        SetWindowBordered(display, screen, w,
-                          !(window->flags & SDL_WINDOW_BORDERLESS));
-    }
+    SetWindowBordered(display, screen, w, !(window->flags & SDL_WINDOW_BORDERLESS));
 
     sizehints = X11_XAllocSizeHints();
     /* Setup the normal size hints */
```

**Comment by Kontrabant** [comment]
That would work, as it just reverts 2de2e9d0 , which was an attempt to work around the flickering, which is now properly fixed.

**Comment by Kontrabant** [comment]
Pull is up, see if that fixes it for you.

**Comment by slouken** [comment]
That does not fix it.

**Comment by slouken** [comment]
Are you on discord? We can interactively troubleshoot this.

**Comment by Kontrabant** [comment]
I just pushed again with another solution that should be more robust. If that doesn't work, I'll hop on Discord.

**Comment by slouken** [comment]
Nope, that didn't work:
```
INFO: Window 3 resized to 3840x2160
INFO: Window 3 moved to 3840,0 (display ASUS PA329CV 32")
```

**Comment by Kontrabant** [comment]
Alright, what Discord server are you on? Let's get this fixed.

**Comment by slouken** [comment]
I'm on the SDL enthusiast discord, I'll be in the sdl-co-working voice chat:
https://discord.gg/AEpHGcfK

**Comment by slouken** [comment]
Almost... DOTA isn't fixed, and I can reproduce the problem by setting the position and size to the main monitor:
`./test/testwm --opengl-window --renderer opengl --fullscreen-desktop --noframe --position 0,0 --geometry 3840x2160`

**Comment by slouken** [comment]
I don't even need --fullscreen-desktop, just specifying --noframe is enough:
`./test/testwm --opengl-window --renderer opengl --position 0,0 --geometry 3840x2160 --noframe`

**Comment by Kontrabant** [comment]
This is reproducing for me now, let me take a look.

**Comment by Kontrabant** [comment]
It's the size hints again. Since the primary display has a top bar, the compositor is trying to "be nice" and put the window on a display where the whole window will actually fit.

**Comment by slouken** [comment]
Ah, that makes sense. For DOTA I can remove the borderless flag when going fullscreen, and I guess we can (and have) document that the window position is only a request. Maybe we should call out this specific case (fullscreen borderless window) so we don't investigate again later when it's reported as a bug?

**Comment by slouken** [comment]
I guess the documentation request is to note that fullscreen desktop and a desktop-sized borderless window are not equivalent, although game developers often try to get fullscreen desktop behavior by using a desktop sized borderless window.

**Comment by Kontrabant** [comment]
I think I've found a workaround: leave the size hints unset until the window is actually mapped, then turn the constraints on. Let me clean this up and you can confirm the fix.

**Comment by slouken** [comment]
Won't that cause the window to show briefly and then bounce to a new size/position?

**Comment by Kontrabant** [comment]
> Won't that cause the window to show briefly and then bounce to a new size/position?

No, but it seems that the compositor will force resize the window into maximized mode. If you then move it to another display where it does fit, it will be expanded to the correct size, but then you can't move it back to the primary, because it no longer fits.

This is slugging it out with the compositor, and it seems that GNOME will not let a non-resizable window, with or without a border, exist on a display where the usable desktop space is less than the content size. I think the solution is manually not making the window non-resizable if the intent is to enter fullscreen, and restoring the non-resizable state when leaving.

To note, this behaves exactly the same on the Wayland backend as well, so it is 100% GNOME doing this.

**Comment by slouken** [comment]
I'm wondering if the better fix is just to pass some flag (pending flags?) so the window creation function knows that it'll be a fullscreen window and we can skip setting borderless like we did before?

**Comment by slouken** [comment]
It won't fix borderless windows that are the size of the desktop, but I think that's okay?

**Comment by Kontrabant** [comment]
I'm seeing this behavior regardless of whether the window has borders turned on or not. It seems to depend on the size of the window content area.

Another possibility is clamping the content size to the usable desktop bounds when the window position is defined. See: https://github.com/libsdl-org/SDL/commit/a4b8d9a5c7505867743c929d4465e4932758a8d6

This seems to work reliably from my testing.

**Comment by slouken** [comment]
> I'm seeing this behavior regardless of whether the window has borders turned on or not. It seems to depend on the size of the window content area.
> 
> Another possibility is clamping the content size to the usable desktop bounds when the window position is defined. See: [a4b8d9a](https://github.com/libsdl-org/SDL/commit/a4b8d9a5c7505867743c929d4465e4932758a8d6)

I guess the question is which is better, getting the size you want, or getting the position you want? For windows that aren't resizable, I tend to think that having the requested size is more important.

**Comment by Kontrabant** [comment]
I think I have a method that will work for both cases. In the case of a non-resizable window that immediately becomes fullscreen, we set the pending flag and make the initial window small enough that it will definitely be placed where we want it, and set a flag blocking resize messages until the window actually becomes fullscreen to mask the bogus size. When leaving fullscreen, we just have to make sure to restore the limits, and everything will be normal. At that point the window manager might move the window to someplace it deems a better fit, but that is what it is.

I have it prototyped, and it seems to work well, but I want to look at it tomorrow with fresh eyes and do more testing. https://github.com/Kontrabant/SDL/commit/764af3c2763f09bb024d9cfb18dfb85372efad2c

**Comment by slouken** [comment]
Sounds good.

**Comment by Kontrabant** [comment]
Took a step back, reevaluated, and came up with this much simpler, cleaner solution that has same outcome and doesn't involve fighting with the window manager. On my system with both displays set to the same resolution and running the repro case, the window is placed on the correct display 100% of the time over a couple dozen tries.
